/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once
#include <layout_engine/AnuMacros.h>

ANU_EXTERN_C_BEGIN

ANU_ENUM_DECL(
    ANUAlign,
    ANUAlignAuto,
    ANUAlignFlexStart,
    ANUAlignCenter,
    ANUAlignFlexEnd,
    ANUAlignStretch,
    ANUAlignBaseline,
    ANUAlignSpaceBetween,
    ANUAlignSpaceAround,
    ANUAlignSpaceEvenly)

ANU_ENUM_DECL(
    ANUBoxSizing,
    ANUBoxSizingBorderBox,
    ANUBoxSizingContentBox)

ANU_ENUM_DECL(
    ANUDimension,
    ANUDimensionWidth,
    ANUDimensionHeight)

ANU_ENUM_DECL(
    ANUDirection,
    ANUDirectionInherit,
    ANUDirectionLTR,
    ANUDirectionRTL)

ANU_ENUM_DECL(
    ANUDisplay,
    ANUDisplayFlex,
    ANUDisplayNone,
    ANUDisplayContents)

ANU_ENUM_DECL(
    ANUEdge,
    ANUEdgeLeft,
    ANUEdgeTop,
    ANUEdgeRight,
    ANUEdgeBottom,
    ANUEdgeStart,
    ANUEdgeEnd,
    ANUEdgeHorizontal,
    ANUEdgeVertical,
    ANUEdgeAll)

ANU_ENUM_DECL(
    ANUErrata,
    ANUErrataNone = 0,
    ANUErrataStretchFlexBasis = 1,
    ANUErrataAbsolutePositionWithoutInsetsExcludesPadding = 2,
    ANUErrataAbsolutePercentAgainstInnerSize = 4,
    ANUErrataAll = 2147483647,
    ANUErrataClassic = 2147483646)
ANU_DEFINE_ENUM_FLAG_OPERATORS(ANUErrata)

ANU_ENUM_DECL(
    ANUExperimentalFeature,
    ANUExperimentalFeatureWebFlexBasis)

ANU_ENUM_DECL(
    ANUFlexDirection,
    ANUFlexDirectionColumn,
    ANUFlexDirectionColumnReverse,
    ANUFlexDirectionRow,
    ANUFlexDirectionRowReverse)

ANU_ENUM_DECL(
    ANUGutter,
    ANUGutterColumn,
    ANUGutterRow,
    ANUGutterAll)

ANU_ENUM_DECL(
    ANUJustify,
    ANUJustifyFlexStart,
    ANUJustifyCenter,
    ANUJustifyFlexEnd,
    ANUJustifySpaceBetween,
    ANUJustifySpaceAround,
    ANUJustifySpaceEvenly)

ANU_ENUM_DECL(
    ANULogLevel,
    ANULogLevelError,
    ANULogLevelWarn,
    ANULogLevelInfo,
    ANULogLevelDebug,
    ANULogLevelVerbose,
    ANULogLevelFatal)

ANU_ENUM_DECL(
    ANUMeasureMode,
    ANUMeasureModeUndefined,
    ANUMeasureModeExactly,
    ANUMeasureModeAtMost)

ANU_ENUM_DECL(
    ANUNodeType,
    ANUNodeTypeDefault,
    ANUNodeTypeText)

ANU_ENUM_DECL(
    ANUOverflow,
    ANUOverflowVisible,
    ANUOverflowHidden,
    ANUOverflowScroll)

ANU_ENUM_DECL(
    ANUPositionType,
    ANUPositionTypeStatic,
    ANUPositionTypeRelative,
    ANUPositionTypeAbsolute)

ANU_ENUM_DECL(
    ANUUnit,
    ANUUnitUndefined,
    ANUUnitPoint,
    ANUUnitPercent,
    ANUUnitAuto)

ANU_ENUM_DECL(
    ANUWrap,
    ANUWrapNoWrap,
    ANUWrapWrap,
    ANUWrapWrapReverse)

ANU_EXTERN_C_END
