/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#include <layout_engine/AnuEnums.h>

const char* ANUAlignToString(const ANUAlign value) {
  switch (value) {
    case ANUAlignAuto:
      return "auto";
    case ANUAlignFlexStart:
      return "flex-start";
    case ANUAlignCenter:
      return "center";
    case ANUAlignFlexEnd:
      return "flex-end";
    case ANUAlignStretch:
      return "stretch";
    case ANUAlignBaseline:
      return "baseline";
    case ANUAlignSpaceBetween:
      return "space-between";
    case ANUAlignSpaceAround:
      return "space-around";
    case ANUAlignSpaceEvenly:
      return "space-evenly";
  }
  return "unknown";
}

const char* ANUBoxSizingToString(const ANUBoxSizing value) {
  switch (value) {
    case ANUBoxSizingBorderBox:
      return "border-box";
    case ANUBoxSizingContentBox:
      return "content-box";
  }
  return "unknown";
}

const char* ANUDimensionToString(const ANUDimension value) {
  switch (value) {
    case ANUDimensionWidth:
      return "width";
    case ANUDimensionHeight:
      return "height";
  }
  return "unknown";
}

const char* ANUDirectionToString(const ANUDirection value) {
  switch (value) {
    case ANUDirectionInherit:
      return "inherit";
    case ANUDirectionLTR:
      return "ltr";
    case ANUDirectionRTL:
      return "rtl";
  }
  return "unknown";
}

const char* ANUDisplayToString(const ANUDisplay value) {
  switch (value) {
    case ANUDisplayFlex:
      return "flex";
    case ANUDisplayNone:
      return "none";
    case ANUDisplayContents:
      return "contents";
  }
  return "unknown";
}

const char* ANUEdgeToString(const ANUEdge value) {
  switch (value) {
    case ANUEdgeLeft:
      return "left";
    case ANUEdgeTop:
      return "top";
    case ANUEdgeRight:
      return "right";
    case ANUEdgeBottom:
      return "bottom";
    case ANUEdgeStart:
      return "start";
    case ANUEdgeEnd:
      return "end";
    case ANUEdgeHorizontal:
      return "horizontal";
    case ANUEdgeVertical:
      return "vertical";
    case ANUEdgeAll:
      return "all";
  }
  return "unknown";
}

const char* ANUErrataToString(const ANUErrata value) {
  switch (value) {
    case ANUErrataNone:
      return "none";
    case ANUErrataStretchFlexBasis:
      return "stretch-flex-basis";
    case ANUErrataAbsolutePositionWithoutInsetsExcludesPadding:
      return "absolute-position-without-insets-excludes-padding";
    case ANUErrataAbsolutePercentAgainstInnerSize:
      return "absolute-percent-against-inner-size";
    case ANUErrataAll:
      return "all";
    case ANUErrataClassic:
      return "classic";
  }
  return "unknown";
}

const char* ANUExperimentalFeatureToString(const ANUExperimentalFeature value) {
  switch (value) {
    case ANUExperimentalFeatureWebFlexBasis:
      return "web-flex-basis";
  }
  return "unknown";
}

const char* ANUFlexDirectionToString(const ANUFlexDirection value) {
  switch (value) {
    case ANUFlexDirectionColumn:
      return "column";
    case ANUFlexDirectionColumnReverse:
      return "column-reverse";
    case ANUFlexDirectionRow:
      return "row";
    case ANUFlexDirectionRowReverse:
      return "row-reverse";
  }
  return "unknown";
}

const char* ANUGutterToString(const ANUGutter value) {
  switch (value) {
    case ANUGutterColumn:
      return "column";
    case ANUGutterRow:
      return "row";
    case ANUGutterAll:
      return "all";
  }
  return "unknown";
}

const char* ANUJustifyToString(const ANUJustify value) {
  switch (value) {
    case ANUJustifyFlexStart:
      return "flex-start";
    case ANUJustifyCenter:
      return "center";
    case ANUJustifyFlexEnd:
      return "flex-end";
    case ANUJustifySpaceBetween:
      return "space-between";
    case ANUJustifySpaceAround:
      return "space-around";
    case ANUJustifySpaceEvenly:
      return "space-evenly";
  }
  return "unknown";
}

const char* ANULogLevelToString(const ANULogLevel value) {
  switch (value) {
    case ANULogLevelError:
      return "error";
    case ANULogLevelWarn:
      return "warn";
    case ANULogLevelInfo:
      return "info";
    case ANULogLevelDebug:
      return "debug";
    case ANULogLevelVerbose:
      return "verbose";
    case ANULogLevelFatal:
      return "fatal";
  }
  return "unknown";
}

const char* ANUMeasureModeToString(const ANUMeasureMode value) {
  switch (value) {
    case ANUMeasureModeUndefined:
      return "undefined";
    case ANUMeasureModeExactly:
      return "exactly";
    case ANUMeasureModeAtMost:
      return "at-most";
  }
  return "unknown";
}

const char* ANUNodeTypeToString(const ANUNodeType value) {
  switch (value) {
    case ANUNodeTypeDefault:
      return "default";
    case ANUNodeTypeText:
      return "text";
  }
  return "unknown";
}

const char* ANUOverflowToString(const ANUOverflow value) {
  switch (value) {
    case ANUOverflowVisible:
      return "visible";
    case ANUOverflowHidden:
      return "hidden";
    case ANUOverflowScroll:
      return "scroll";
  }
  return "unknown";
}

const char* ANUPositionTypeToString(const ANUPositionType value) {
  switch (value) {
    case ANUPositionTypeStatic:
      return "static";
    case ANUPositionTypeRelative:
      return "relative";
    case ANUPositionTypeAbsolute:
      return "absolute";
  }
  return "unknown";
}

const char* ANUUnitToString(const ANUUnit value) {
  switch (value) {
    case ANUUnitUndefined:
      return "undefined";
    case ANUUnitPoint:
      return "point";
    case ANUUnitPercent:
      return "percent";
    case ANUUnitAuto:
      return "auto";
  }
  return "unknown";
}

const char* ANUWrapToString(const ANUWrap value) {
  switch (value) {
    case ANUWrapNoWrap:
      return "no-wrap";
    case ANUWrapWrap:
      return "wrap";
    case ANUWrapWrapReverse:
      return "wrap-reverse";
  }
  return "unknown";
}
