/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Align : uint8_t {
  Auto = ANUAlignAuto,
  FlexStart = ANUAlignFlexStart,
  Center = ANUAlignCenter,
  FlexEnd = ANUAlignFlexEnd,
  Stretch = ANUAlignStretch,
  Baseline = ANUAlignBaseline,
  SpaceBetween = ANUAlignSpaceBetween,
  SpaceAround = ANUAlignSpaceAround,
  SpaceEvenly = ANUAlignSpaceEvenly,
};

template <>
constexpr int32_t ordinalCount<Align>() {
  return 9;
}

constexpr Align scopedEnum(ANUAlign unscoped) {
  return static_cast<Align>(unscoped);
}

constexpr ANUAlign unscopedEnum(Align scoped) {
  return static_cast<ANUAlign>(scoped);
}

inline const char* toString(Align e) {
  return ANUAlignToString(unscopedEnum(e));
}

} // namespace facebook::anu
