/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class BoxSizing : uint8_t {
  BorderBox = ANUBoxSizingBorderBox,
  ContentBox = ANUBoxSizingContentBox,
};

template <>
constexpr int32_t ordinalCount<BoxSizing>() {
  return 2;
}

constexpr BoxSizing scopedEnum(ANUBoxSizing unscoped) {
  return static_cast<BoxSizing>(unscoped);
}

constexpr ANUBoxSizing unscopedEnum(BoxSizing scoped) {
  return static_cast<ANUBoxSizing>(scoped);
}

inline const char* toString(BoxSizing e) {
  return ANUBoxSizingToString(unscopedEnum(e));
}

} // namespace facebook::anu
