/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Dimension : uint8_t {
  Width = ANUDimensionWidth,
  Height = ANUDimensionHeight,
};

template <>
constexpr int32_t ordinalCount<Dimension>() {
  return 2;
}

constexpr Dimension scopedEnum(ANUDimension unscoped) {
  return static_cast<Dimension>(unscoped);
}

constexpr ANUDimension unscopedEnum(Dimension scoped) {
  return static_cast<ANUDimension>(scoped);
}

inline const char* toString(Dimension e) {
  return ANUDimensionToString(unscopedEnum(e));
}

} // namespace facebook::anu
