/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Display : uint8_t {
  Flex = ANUDisplayFlex,
  None = ANUDisplayNone,
  Contents = ANUDisplayContents,
};

template <>
constexpr int32_t ordinalCount<Display>() {
  return 3;
}

constexpr Display scopedEnum(ANUDisplay unscoped) {
  return static_cast<Display>(unscoped);
}

constexpr ANUDisplay unscopedEnum(Display scoped) {
  return static_cast<ANUDisplay>(scoped);
}

inline const char* toString(Display e) {
  return ANUDisplayToString(unscopedEnum(e));
}

} // namespace facebook::anu
