/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Edge : uint8_t {
  Left = ANUEdgeLeft,
  Top = ANUEdgeTop,
  Right = ANUEdgeRight,
  Bottom = ANUEdgeBottom,
  Start = ANUEdgeStart,
  End = ANUEdgeEnd,
  Horizontal = ANUEdgeHorizontal,
  Vertical = ANUEdgeVertical,
  All = ANUEdgeAll,
};

template <>
constexpr int32_t ordinalCount<Edge>() {
  return 9;
}

constexpr Edge scopedEnum(ANUEdge unscoped) {
  return static_cast<Edge>(unscoped);
}

constexpr ANUEdge unscopedEnum(Edge scoped) {
  return static_cast<ANUEdge>(scoped);
}

inline const char* toString(Edge e) {
  return ANUEdgeToString(unscopedEnum(e));
}

} // namespace facebook::anu
