/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Errata : uint32_t {
  None = ANUErrataNone,
  StretchFlexBasis = ANUErrataStretchFlexBasis,
  AbsolutePositionWithoutInsetsExcludesPadding = ANUErrataAbsolutePositionWithoutInsetsExcludesPadding,
  AbsolutePercentAgainstInnerSize = ANUErrataAbsolutePercentAgainstInnerSize,
  All = ANUErrataAll,
  Classic = ANUErrataClassic,
};

ANU_DEFINE_ENUM_FLAG_OPERATORS(Errata)

constexpr Errata scopedEnum(ANUErrata unscoped) {
  return static_cast<Errata>(unscoped);
}

constexpr ANUErrata unscopedEnum(Errata scoped) {
  return static_cast<ANUErrata>(scoped);
}

inline const char* toString(Errata e) {
  return ANUErrataToString(unscopedEnum(e));
}

} // namespace facebook::anu
