/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class ExperimentalFeature : uint8_t {
  WebFlexBasis = ANUExperimentalFeatureWebFlexBasis,
};

template <>
constexpr int32_t ordinalCount<ExperimentalFeature>() {
  return 1;
}

constexpr ExperimentalFeature scopedEnum(ANUExperimentalFeature unscoped) {
  return static_cast<ExperimentalFeature>(unscoped);
}

constexpr ANUExperimentalFeature unscopedEnum(ExperimentalFeature scoped) {
  return static_cast<ANUExperimentalFeature>(scoped);
}

inline const char* toString(ExperimentalFeature e) {
  return ANUExperimentalFeatureToString(unscopedEnum(e));
}

} // namespace facebook::anu
