/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class FlexDirection : uint8_t {
  Column = ANUFlexDirectionColumn,
  ColumnReverse = ANUFlexDirectionColumnReverse,
  Row = ANUFlexDirectionRow,
  RowReverse = ANUFlexDirectionRowReverse,
};

template <>
constexpr int32_t ordinalCount<FlexDirection>() {
  return 4;
}

constexpr FlexDirection scopedEnum(ANUFlexDirection unscoped) {
  return static_cast<FlexDirection>(unscoped);
}

constexpr ANUFlexDirection unscopedEnum(FlexDirection scoped) {
  return static_cast<ANUFlexDirection>(scoped);
}

inline const char* toString(FlexDirection e) {
  return ANUFlexDirectionToString(unscopedEnum(e));
}

} // namespace facebook::anu
