/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Justify : uint8_t {
  FlexStart = ANUJustifyFlexStart,
  Center = ANUJustifyCenter,
  FlexEnd = ANUJustifyFlexEnd,
  SpaceBetween = ANUJustifySpaceBetween,
  SpaceAround = ANUJustifySpaceAround,
  SpaceEvenly = ANUJustifySpaceEvenly,
};

template <>
constexpr int32_t ordinalCount<Justify>() {
  return 6;
}

constexpr Justify scopedEnum(ANUJustify unscoped) {
  return static_cast<Justify>(unscoped);
}

constexpr ANUJustify unscopedEnum(Justify scoped) {
  return static_cast<ANUJustify>(scoped);
}

inline const char* toString(Justify e) {
  return ANUJustifyToString(unscopedEnum(e));
}

} // namespace facebook::anu
