/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class LogLevel : uint8_t {
  Error = ANULogLevelError,
  Warn = ANULogLevelWarn,
  Info = ANULogLevelInfo,
  Debug = ANULogLevelDebug,
  Verbose = ANULogLevelVerbose,
  Fatal = ANULogLevelFatal,
};

template <>
constexpr int32_t ordinalCount<LogLevel>() {
  return 6;
}

constexpr LogLevel scopedEnum(ANULogLevel unscoped) {
  return static_cast<LogLevel>(unscoped);
}

constexpr ANULogLevel unscopedEnum(LogLevel scoped) {
  return static_cast<ANULogLevel>(scoped);
}

inline const char* toString(LogLevel e) {
  return ANULogLevelToString(unscopedEnum(e));
}

} // namespace facebook::anu
