/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class MeasureMode : uint8_t {
  Undefined = ANUMeasureModeUndefined,
  Exactly = ANUMeasureModeExactly,
  AtMost = ANUMeasureModeAtMost,
};

template <>
constexpr int32_t ordinalCount<MeasureMode>() {
  return 3;
}

constexpr MeasureMode scopedEnum(ANUMeasureMode unscoped) {
  return static_cast<MeasureMode>(unscoped);
}

constexpr ANUMeasureMode unscopedEnum(MeasureMode scoped) {
  return static_cast<ANUMeasureMode>(scoped);
}

inline const char* toString(MeasureMode e) {
  return ANUMeasureModeToString(unscopedEnum(e));
}

} // namespace facebook::anu
