/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class NodeType : uint8_t {
  Default = ANUNodeTypeDefault,
  Text = ANUNodeTypeText,
};

template <>
constexpr int32_t ordinalCount<NodeType>() {
  return 2;
}

constexpr NodeType scopedEnum(ANUNodeType unscoped) {
  return static_cast<NodeType>(unscoped);
}

constexpr ANUNodeType unscopedEnum(NodeType scoped) {
  return static_cast<ANUNodeType>(scoped);
}

inline const char* toString(NodeType e) {
  return ANUNodeTypeToString(unscopedEnum(e));
}

} // namespace facebook::anu
