/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Overflow : uint8_t {
  Visible = ANUOverflowVisible,
  Hidden = ANUOverflowHidden,
  Scroll = ANUOverflowScroll,
};

template <>
constexpr int32_t ordinalCount<Overflow>() {
  return 3;
}

constexpr Overflow scopedEnum(ANUOverflow unscoped) {
  return static_cast<Overflow>(unscoped);
}

constexpr ANUOverflow unscopedEnum(Overflow scoped) {
  return static_cast<ANUOverflow>(scoped);
}

inline const char* toString(Overflow e) {
  return ANUOverflowToString(unscopedEnum(e));
}

} // namespace facebook::anu
