/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class PositionType : uint8_t {
  Static = ANUPositionTypeStatic,
  Relative = ANUPositionTypeRelative,
  Absolute = ANUPositionTypeAbsolute,
};

template <>
constexpr int32_t ordinalCount<PositionType>() {
  return 3;
}

constexpr PositionType scopedEnum(ANUPositionType unscoped) {
  return static_cast<PositionType>(unscoped);
}

constexpr ANUPositionType unscopedEnum(PositionType scoped) {
  return static_cast<ANUPositionType>(scoped);
}

inline const char* toString(PositionType e) {
  return ANUPositionTypeToString(unscopedEnum(e));
}

} // namespace facebook::anu
