/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py
// clang-format off
#pragma once

#include <cstdint>
#include <layout_engine/AnuEnums.h>
#include <layout_engine/enums/AnuEnums.h>

namespace facebook::anu {

enum class Unit : uint8_t {
  Undefined = ANUUnitUndefined,
  Point = ANUUnitPoint,
  Percent = ANUUnitPercent,
  Auto = ANUUnitAuto,
};

template <>
constexpr int32_t ordinalCount<Unit>() {
  return 4;
}

constexpr Unit scopedEnum(ANUUnit unscoped) {
  return static_cast<Unit>(unscoped);
}

constexpr ANUUnit unscopedEnum(Unit scoped) {
  return static_cast<ANUUnit>(scoped);
}

inline const char* toString(Unit e) {
  return ANUUnitToString(unscopedEnum(e));
}

} // namespace facebook::anu
